#!/usr/bin/env bash
#
# Boots the full stack (Phoenix API + Next.js frontend) behind ngrok.
#
#   - Two ngrok HTTP tunnels (api → :4000, web → :3000)
#   - Frontend .env.local rewritten with the public API URL
#   - Phoenix booted with CORS_ORIGINS pointing at the public web URL
#
# Requirements: ngrok (authenticated), python3, curl, mix, bun.
#
# Press Ctrl-C to tear everything down.

set -euo pipefail

# --- locate the project regardless of where the script is invoked from ----
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
API_DIR="$ROOT/api/cura"
WEB_DIR="$ROOT/clients/web/cura"
TMPDIR_LOCAL="$(mktemp -d -t cura-ngrok-XXXXXX)"

NGROK_CONFIG="$TMPDIR_LOCAL/ngrok.yml"
NGROK_LOG="$TMPDIR_LOCAL/ngrok.log"
PHX_LOG="$TMPDIR_LOCAL/phx.log"
WEB_LOG="$TMPDIR_LOCAL/web.log"
ENV_FILE="$WEB_DIR/.env.local"
ENV_BACKUP="$TMPDIR_LOCAL/env.local.bak"

NGROK_PID=""
PHX_PID=""
WEB_PID=""

cleanup() {
  echo
  echo "→ tearing down…"
  for pid in "$WEB_PID" "$PHX_PID" "$NGROK_PID"; do
    [ -n "$pid" ] && kill "$pid" 2>/dev/null || true
  done
  # restore previous .env.local if we replaced one
  if [ -f "$ENV_BACKUP" ]; then
    mv "$ENV_BACKUP" "$ENV_FILE"
    echo "  • restored $ENV_FILE"
  elif [ -f "$ENV_FILE.cura-ngrok" ]; then
    rm -f "$ENV_FILE"
    rm -f "$ENV_FILE.cura-ngrok"
    echo "  • removed $ENV_FILE"
  fi
  rm -rf "$TMPDIR_LOCAL"
  echo "  • done."
}
trap cleanup EXIT INT TERM

# --- preflight checks -----------------------------------------------------
require() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "✗ $1 is required but not installed." >&2
    [ -n "${2-}" ] && echo "  $2" >&2
    exit 1
  }
}
require ngrok    "Install from https://ngrok.com/download and run 'ngrok config add-authtoken <token>' once."
require python3
require curl
require mix      "Install Elixir + Phoenix."
require bun      "Install from https://bun.sh."

[ -d "$API_DIR" ] || { echo "✗ API dir not found: $API_DIR" >&2; exit 1; }
[ -d "$WEB_DIR" ] || { echo "✗ Web dir not found: $WEB_DIR" >&2; exit 1; }

# --- free up our ports if anything's still running ------------------------
free_port() {
  local port="$1"
  local pids
  pids=$(lsof -ti tcp:"$port" 2>/dev/null || true)
  if [ -n "$pids" ]; then
    echo "  • killing processes on :$port ($pids)"
    kill -9 $pids 2>/dev/null || true
  fi
}
echo "→ freeing ports 3000 and 4000…"
free_port 3000
free_port 4000

# --- ngrok config ---------------------------------------------------------
cat > "$NGROK_CONFIG" <<EOF
version: "2"
tunnels:
  api:
    proto: http
    addr: 4000
  web:
    proto: http
    addr: 3000
EOF

# --- start ngrok ----------------------------------------------------------
echo "→ starting ngrok…"
ngrok start --config "$NGROK_CONFIG" --all > "$NGROK_LOG" 2>&1 &
NGROK_PID=$!

# wait for ngrok's local API to come up and report both tunnels
echo -n "  • waiting for tunnels"
for _ in $(seq 1 30); do
  echo -n "."
  if curl -fs http://127.0.0.1:4040/api/tunnels >/dev/null 2>&1; then
    count=$(curl -fs http://127.0.0.1:4040/api/tunnels \
      | python3 -c 'import json,sys; print(len(json.load(sys.stdin)["tunnels"]))')
    if [ "$count" -ge 2 ]; then
      echo " up."
      break
    fi
  fi
  sleep 0.5
done

TUNNELS_JSON=$(curl -fs http://127.0.0.1:4040/api/tunnels || true)
if [ -z "$TUNNELS_JSON" ]; then
  echo
  echo "✗ ngrok didn't come up. Last 20 lines of log:" >&2
  tail -20 "$NGROK_LOG" >&2
  exit 1
fi

read API_URL WEB_URL <<EOF
$(echo "$TUNNELS_JSON" | python3 -c '
import json, sys
data = json.load(sys.stdin)
out = {t["name"]: t["public_url"] for t in data["tunnels"]}
api = out.get("api", "")
web = out.get("web", "")
# prefer the https variant if both are present (ngrok lists both on free tier)
print(api, web)
')
EOF

if [ -z "$API_URL" ] || [ -z "$WEB_URL" ]; then
  echo "✗ couldn't read tunnel URLs from ngrok." >&2
  echo "$TUNNELS_JSON" | python3 -m json.tool >&2
  exit 1
fi

echo "  • api → $API_URL"
echo "  • web → $WEB_URL"

# --- write .env.local for the frontend ------------------------------------
echo "→ writing $ENV_FILE…"
if [ -f "$ENV_FILE" ]; then
  cp "$ENV_FILE" "$ENV_BACKUP"
else
  : > "$ENV_FILE.cura-ngrok"   # marker so cleanup knows to delete the file
fi
cat > "$ENV_FILE" <<EOF
# Generated by scripts/dev-with-ngrok.sh — restored on exit.
NEXT_PUBLIC_API_BASE_URL=$API_URL
API_BASE_URL=$API_URL
EOF

# --- start phoenix --------------------------------------------------------
echo "→ starting phx.server…"
(
  cd "$API_DIR"
  CORS_ORIGINS="$WEB_URL,$API_URL" mix phx.server >"$PHX_LOG" 2>&1
) &
PHX_PID=$!

# --- start next.js --------------------------------------------------------
echo "→ starting next dev…"
(
  cd "$WEB_DIR"
  bun dev >"$WEB_LOG" 2>&1
) &
WEB_PID=$!

# --- wait for both to be reachable ---------------------------------------
wait_for_http() {
  local url="$1" name="$2"
  echo -n "  • waiting for $name"
  for _ in $(seq 1 60); do
    echo -n "."
    if curl -fs -o /dev/null -m 2 "$url"; then
      echo " up."
      return 0
    fi
    sleep 1
  done
  echo " timed out."
  return 1
}
wait_for_http "http://127.0.0.1:4000/api/me" phx || true   # 401 still counts as "reachable"
wait_for_http "http://127.0.0.1:3000"          web || true

echo
echo "═══════════════════════════════════════════════════════════════"
echo " Cura is up behind ngrok"
echo "─────────────────────────────────────────────────────────────"
echo "  Frontend (open this in two browsers):  $WEB_URL"
echo "  API:                                   $API_URL"
echo "  ngrok inspector:                       http://127.0.0.1:4040"
echo "─────────────────────────────────────────────────────────────"
echo "  Test accounts:"
echo "    doctor1@cura.pt  / password1234"
echo "    patient7@cura.pt / password1234"
echo "─────────────────────────────────────────────────────────────"
echo "  Logs:"
echo "    ngrok : $NGROK_LOG"
echo "    phx   : $PHX_LOG"
echo "    web   : $WEB_LOG"
echo "═══════════════════════════════════════════════════════════════"
echo "Ctrl-C to stop everything."

# block until any child dies, then trigger cleanup
wait -n "$NGROK_PID" "$PHX_PID" "$WEB_PID" 2>/dev/null || true
